<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="IO" Id="{bd3ef4b5-36ef-4299-8510-24603ab157ac}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM IO
VAR
	//Link you hardware IO to these variables.
	//You can rename these variables as you like.
	DI1 AT %I* : BOOL;
	DI2 AT %I* : BOOL;	
	DI3 AT %I* : BOOL;
	DI4 AT %I* : BOOL;	
	DI5 AT %I* : BOOL;	
	DI6 AT %I* : BOOL;
	DI7 AT %I* : BOOL;	
	DI8 AT %I* : BOOL;	
	DI9 AT %I* : BOOL;
	DI10 AT %I* : BOOL;
	DI11 AT %I* : BOOL;
	DI12 AT %I* : BOOL;
	DI13 AT %I* : BOOL;
	DI14 AT %I* : BOOL;
	DI15 AT %I* : BOOL;
	DI16 AT %I* : BOOL;

	
	DO1 AT %Q* : BOOL;
	DO2 AT %Q* : BOOL;
	DO3 AT %Q* : BOOL;
	DO4 AT %Q* : BOOL;
	DO5 AT %Q* : BOOL;
	DO6 AT %Q* : BOOL;
	DO7 AT %Q* : BOOL;	
	
	AI1 AT %I* : INT;
	AI2 AT %I* : INT;
	AI3 AT %I* : INT;
	
	AO1 AT %Q* : INT;
	AO2 AT %Q* : INT;
	AO3 AT %Q* : INT;

	EMCOK  AT %I*:BOOL; //Emergency stop OK.
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="IO">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>