<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{34dbeb6e-0188-42c2-aa4f-4993de0a93ee}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//Variables of type AXIS_REF to your motors.
	//Add more motors if you need to.
	
	motor_x0 : AxisBase;
	motor_y0 : AxisBase;
	motor_z0 : AxisBase;
	
	motor_a0 : AxisBase;
	motor_b0 : AxisBase;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[motor_x0();
motor_y0();
motor_z0();
                    
motor_a0();
motor_b0();


IO();
Recorder();
EtherCatDiagnosis();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="9" Count="1" />
      <LineId Id="12" Count="0" />
      <LineId Id="53" Count="1" />
      <LineId Id="35" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="85" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>